[package]
name = "2-seam-carving"
version = "0.1.0"
authors = ["Caspar Krieger <caspar@asparck.com>"]

[dependencies]
getopts = "*"
time = "*"

[dependencies.lodepng]
git = "https://github.com/pornel/lodepng-rust.git"

[profile.release]
debug = true

